/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as DataRouteImport } from './routes/data'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CampaignReviewRouteImport } from './routes/campaign-review'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignReviewIndexRouteImport } from './routes/campaign-review.index'
import { Route as CampaignReviewCampaignRouteImport } from './routes/campaign-review.$campaign'
import { Route as ApiPublicHooksSyncSnapshotsRouteImport } from './routes/api/public/hooks/sync-snapshots'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignReviewRoute = CampaignReviewRouteImport.update({
  id: '/campaign-review',
  path: '/campaign-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignReviewIndexRoute = CampaignReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignReviewRoute,
} as any)
const CampaignReviewCampaignRoute = CampaignReviewCampaignRouteImport.update({
  id: '/$campaign',
  path: '/$campaign',
  getParentRoute: () => CampaignReviewRoute,
} as any)
const ApiPublicHooksSyncSnapshotsRoute =
  ApiPublicHooksSyncSnapshotsRouteImport.update({
    id: '/api/public/hooks/sync-snapshots',
    path: '/api/public/hooks/sync-snapshots',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign-review': typeof CampaignReviewRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/connections': typeof ConnectionsRoute
  '/data': typeof DataRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/campaign-review/$campaign': typeof CampaignReviewCampaignRoute
  '/campaign-review/': typeof CampaignReviewIndexRoute
  '/api/public/hooks/sync-snapshots': typeof ApiPublicHooksSyncSnapshotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/connections': typeof ConnectionsRoute
  '/data': typeof DataRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/campaign-review/$campaign': typeof CampaignReviewCampaignRoute
  '/campaign-review': typeof CampaignReviewIndexRoute
  '/api/public/hooks/sync-snapshots': typeof ApiPublicHooksSyncSnapshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign-review': typeof CampaignReviewRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/connections': typeof ConnectionsRoute
  '/data': typeof DataRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/campaign-review/$campaign': typeof CampaignReviewCampaignRoute
  '/campaign-review/': typeof CampaignReviewIndexRoute
  '/api/public/hooks/sync-snapshots': typeof ApiPublicHooksSyncSnapshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaign-review'
    | '/campaigns'
    | '/connections'
    | '/data'
    | '/launch'
    | '/login'
    | '/schedule'
    | '/settings'
    | '/campaign-review/$campaign'
    | '/campaign-review/'
    | '/api/public/hooks/sync-snapshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/connections'
    | '/data'
    | '/launch'
    | '/login'
    | '/schedule'
    | '/settings'
    | '/campaign-review/$campaign'
    | '/campaign-review'
    | '/api/public/hooks/sync-snapshots'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaign-review'
    | '/campaigns'
    | '/connections'
    | '/data'
    | '/launch'
    | '/login'
    | '/schedule'
    | '/settings'
    | '/campaign-review/$campaign'
    | '/campaign-review/'
    | '/api/public/hooks/sync-snapshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignReviewRoute: typeof CampaignReviewRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DataRoute: typeof DataRoute
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicHooksSyncSnapshotsRoute: typeof ApiPublicHooksSyncSnapshotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign-review': {
      id: '/campaign-review'
      path: '/campaign-review'
      fullPath: '/campaign-review'
      preLoaderRoute: typeof CampaignReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign-review/': {
      id: '/campaign-review/'
      path: '/'
      fullPath: '/campaign-review/'
      preLoaderRoute: typeof CampaignReviewIndexRouteImport
      parentRoute: typeof CampaignReviewRoute
    }
    '/campaign-review/$campaign': {
      id: '/campaign-review/$campaign'
      path: '/$campaign'
      fullPath: '/campaign-review/$campaign'
      preLoaderRoute: typeof CampaignReviewCampaignRouteImport
      parentRoute: typeof CampaignReviewRoute
    }
    '/api/public/hooks/sync-snapshots': {
      id: '/api/public/hooks/sync-snapshots'
      path: '/api/public/hooks/sync-snapshots'
      fullPath: '/api/public/hooks/sync-snapshots'
      preLoaderRoute: typeof ApiPublicHooksSyncSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampaignReviewRouteChildren {
  CampaignReviewCampaignRoute: typeof CampaignReviewCampaignRoute
  CampaignReviewIndexRoute: typeof CampaignReviewIndexRoute
}

const CampaignReviewRouteChildren: CampaignReviewRouteChildren = {
  CampaignReviewCampaignRoute: CampaignReviewCampaignRoute,
  CampaignReviewIndexRoute: CampaignReviewIndexRoute,
}

const CampaignReviewRouteWithChildren = CampaignReviewRoute._addFileChildren(
  CampaignReviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignReviewRoute: CampaignReviewRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  ConnectionsRoute: ConnectionsRoute,
  DataRoute: DataRoute,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicHooksSyncSnapshotsRoute: ApiPublicHooksSyncSnapshotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
